namespace Gu.Wpf.DataGrid2D.Demo
{
    using System;
    using System.Windows.Controls;

    /// <summary>
    /// Interaction logic for TemplateColumnSelectorView.xaml
    /// </summary>
    public partial class TemplateColumnSelectorView : UserControl
    {
        public TemplateColumnSelectorView()
        {
            InitializeComponent();
        }

        private void DataGrid_OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
        }

        private void DataGrid_OnAutoGeneratedColumns(object sender, EventArgs e)
        {
        }
    }
}
